runtime: python312
app_engine_apis: true
instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /vendor
  static_dir: vendor

- url: /img
  static_dir: img
