runtime: python27
api_version: 1
threadsafe: false
instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /vendor
  static_dir: vendor

- url: /.*
  script: app.py
  secure: always
